spring:
  application:
    #指定配置文件前缀
    name: ui
  cloud:
    config:
      #git 仓库版本或是本地文件native则无效
      label: master
      #config server 地址
      uri: http://localhost:8888
      #指定配置文件后缀
      profile: dev
#监听服务配置
management:
  endpoints:
    web:
      exposure:
        # *是关键字 公开所有监听服务
        include: "*"
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
