spring:
  kafka:
    producer:
      #请求完整性条件 all 最可靠 性能最低，发送时阻塞
      acks: all
      #发送失败 重试次数 设置0 避免出现重复消息
      retries: 0
      #指定单次请求缓冲大小
      batch-size: 16384
      #缓冲区最大值
      buffer-memory: 33554432
      #compression-type: 压缩格式
    consumer:
      #消费者分组
      group-id: test
      autoOffsetReset: earliest
      properties:
        #设置主题信息更新间隔 默认无法设置 好像是5分钟 设置后延时3秒更新，不懂啊...
        metadata.max.age.ms: 10000
      #禁用自动提交offset
      enable-auto-commit: false
    #kafka机器地址
    bootstrap-servers: localhost:9090
    listener:
      #开启手动提交
      ack-mode: manual_immediate
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/message_center
    username: root
    password: w123456

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

info:
    app:
      #导入pom文件信息
      name: '@project.name@'
      description: '@project.description@'
      version: '@project.version@'
      parent-version: '@project.parent.version@'